nameOverride: ""
serviceAccount:
  annotations: {}
  name: secrets-store-csi-driver-provider-gcp
image:
  repository: us-docker.pkg.dev/secretmanager-csi/secrets-store-csi-driver-provider-gcp/plugin
  pullPolicy: IfNotPresent
  hash: sha256:216878a9322ae8e966b886fd03de187b294c15124e67071740cee46e7e7bcf19
app: csi-secrets-store-provider-gcp
podAnnotations: {}
resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 50m
    memory: 100Mi
priorityClassName: ""
nodeSelector:
  kubernetes.io/os: linux
tolerations: []
affinity: {}
